# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_arm1:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  joint_arm2:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  joint_arm3:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  joint_arm4:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  joint_arm5:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0
  joint_arm6:
    has_velocity_limits: true
    max_velocity: 6.5
    has_acceleration_limits: false
    max_acceleration: 0